### ISSUE TITLE
Use tinykeys instead of react-use-keypress

### ISSUE THREAD

**Issue by chloe463** [potsbo/fasty-frontend#39]
https://www.npmjs.com/package/tinykeys を試してみたい。

- TypeScript 実装なので型定義を含んでいる (react-use-keypress はこれがなくて今は自前で用意している)
- かなり宣言的に書けそう
  - 1つの keypress だけではなく、複数文字の入力や、複合キーの入力にも対応している
- 軽い (~400B と謳っている)

圧倒的に優れているとか、ユースケースにマッチしているというわけではなさそうだが、試してみたい気持ちはある。

**Comment by potsbo** [comment]
入れてみて困ったらまたその時考えればいいし、この repository は楽しい遊び場なので深く考えずにガンガンやっちゃって大丈夫です。

**Comment by chloe463** [comment]
ちょっと入れてやってみたが、↓でやってみる「`trapKeys` に入っている候補文字に引っかかったら」みたいな使い方はできないみたいだった。
https://github.com/potsbo/fasty-frontend/blob/bc1fcbe1ea4827733b7519e3c8746d84a63a6183/src/TypeTask.tsx#L112-L121 

tinyKeys の usecase 的にはショートカットコマンドを実現したいみたいなときに使えば良さそうだと判断して今回は入れない。
